all: diseno.pdf

diseno.pdf: diseno.tex
	pdflatex diseno.tex && \
	pdflatex diseno.tex && \
	pdflatex diseno.tex

clean:
	rm -f diseno.toc diseno.log diseno.aux diseno.pdf diseno.lof diseno.lot diseno.out
