all: implementacion.pdf

implementacion.pdf: implementacion.tex
	pdflatex implementacion.tex && \
	pdflatex implementacion.tex && \
	pdflatex implementacion.tex

clean:
	rm -f implementacion.toc implementacion.log implementacion.aux implementacion.pdf implementacion.lof implementacion.lot implementacion.out
